name: Tavan Avcisi Otomasyonu

on:
  schedule:
    - cron: '15 07 * * 1-5'  # TR Saati 10:15
    - cron: '30 14 * * 1-5'  # TR Saati 17:30
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Kutuphaneleri Yukle
        run: |
          pip install pandas yfinance requests numpy
          pip install --upgrade pip
          # Pandas-ta için en garanti kurulum yöntemi:
          pip install https://github.com/twopirllc/pandas-ta/archive/refs/heads/development.zip
      - name: Robotu Atesle
        run: python ana_kontrol.py
